name = "solana-bot-worker-63b7"
main = "build/worker.js"
compatibility_date = "2024-04-04"
workers_dev = true
# compatibility_flags = [ "nodejs_compat" ]


[vars]
TELEGRAM_CHAT_ID=6902486057
MAX_SOL_BUY=30000000
MAX_USDC_BUY=5000000
NODE_VERSION=20
ENABLE_EXECUTION=false
